name = "gleam_chrono"
version = "0.0.1"
licences = ["Apache-2.0"]
description = "Date and time library for Gleam"
repository = { type = "github", user = "HarryET", repo = "gleam_chrono" }
links = [
    # { title = "Website", href = "https://gleam.harryet.xyz/chrono" },
]

[dependencies]
gleam_stdlib = "~> 0.21"

[dev-dependencies]
gleeunit = "~> 0.6"
